language: julia
sudo: required
dist: trusty
os:
  - linux
julia:
  - 0.6
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
notifications:
  email: false
git:
  depth: 99999999
before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then install_fdb.sh; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("FoundationDB"); Pkg.test("FoundationDB"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("FoundationDB")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("FoundationDB")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
